- src/components/homepage/LatestBundles.jsx
- src/components/homepage/LatestUserOps.jsx
- src/components/homepage/NetworkFilter.jsx
- src/pages/index.js
- src/utils/constants.js
Adding filtring based on network to the home page.
> adding network filter to home page

- public/images/Vector345.svg
- public/images/icon-container (26).svg
- public/images/icon-container (27).svg
- src/components/common/Token.tsx
- src/components/common/table/Pagination.tsx
- src/components/globals/searchblock/Options.tsx
- src/components/globals/searchblock/Searchblock.tsx
- src/views/home/Home.tsx
- src/views/user_operations/UserOperations.tsx
- src/views/user_operations/table_data.json
This pull request adds new functionality to the table pagination and search components. The table pagination now has additional functionality similar to the MUI component, making it easier to navigate through large datasets. Additionally, a select option has been added to the search component on the home page, allowing users to filter search results by category.
These changes improve the usability and functionality of the application, making it easier for users to find and navigate through the data. The code has been tested and is ready for review. Thank you for your consideration.
> Added Table Pagination and Search Select Option

- public/images/icon-container (28).svg
- public/images/icon-container45.svg
- src/components/common/chip/Chip.tsx
- src/components/globals/recent_metrics/RecentMetrics.tsx
- yarn.lock
I have implemented the button functionality. When the user clicks on this button, its color will change to a darker shade similar to that of your reference website.
> Implementation of Dark Mode Button Color Change on User Click

- src/components/globals/searchblock/Options.tsx
I have just removed the blur effect
> background blur fix closes 16

- package.json
- src/components/Skeleton.tsx
- src/components/common/Token.tsx
- src/components/common/copy_button/CopyButton.tsx
- src/components/common/table/Pagination.tsx
- src/components/common/table/Table.tsx
- src/components/globals/recent_metrics/Chart.tsx
- src/components/globals/recent_metrics/NetworkSelector.tsx
- src/components/globals/recent_metrics/RecentMetrics.tsx
- src/components/globals/searchblock/Options.tsx
- src/views/home/Home.tsx
- src/views/latestBundles/Bundles.tsx
- src/views/latestUserOps/UserOperations.tsx
- yarn.lock
issues for Pagination for bundle list and user operation fixed.
> issues for Pagination for bundlelist and user operation fixed.

- src/components/common/apiCalls/jiffyApis.tsx
- src/components/common/table/Pagination.tsx
- src/components/common/table/Table.tsx
- src/views/latestBundles/Bundles.tsx
- src/views/latestUserOps/UserOperations.tsx
Added logic for pagination. To test , you can open the preview link and head to latestUserOps or latestBundles page and try changing the pages.
> adding pagination ogic

- src/components/common/apiCalls/jiffyApis.tsx
- src/pages/bundler/[...slug].tsx
- src/views/bundle/TransactionDetails.tsx
- src/views/bundler/Bundler.tsx
- src/views/bundler/HeaderSection.tsx
- src/views/userOp/HeaderSection.tsx
- src/views/userOp/TransactionDetails.tsx
- src/views/userOp/UserOperation.tsx
implemented bundler changes with the #66.
> implemented bundler changes with the #66.

- src/components/common/apiCalls/jiffyApis.tsx
- src/components/common/status/Status.tsx
- src/components/common/table/Table.tsx
- src/pages/_app.tsx
- src/pages/account/[...slug].tsx
- src/pages/block/[...slug].tsx
- src/pages/bundle/[...slug].tsx
- src/pages/bundler/[...slug].tsx
- src/pages/index.tsx
- src/pages/paymaster/[...slug].tsx
- src/pages/recentBundles.tsx
- src/pages/recentUserOps.tsx
- src/pages/userOpHash/[...slug].tsx
- src/views/account/TransactionDetails.tsx
- src/views/bundle/TransactionDetails.tsx
- src/views/recentPaymentMaster/TransactionDetails.tsx
- src/views/userOp/DeveloperDetails.tsx
- src/views/userOp/TransactionDetails.tsx
implemented mobile view for the bundler,account,paymaster.
> implemented mobile view for the bundler,account,paymaster.

- src/views/recentPaymentMaster/recentPaymentMaster.tsx
#98 Bottom section not aligned with top ones
i have aligned bottom section with top once
> dheerajsingh0:98-Bottom-section-not-aligned-with-top-ones

- src/components/common/table/Table.tsx
#97 dheerajsingh0 fixed-sort is not fuctional maybe removing hover pointer.
> 97 dheerajsingh0 sort is not fuctional maybe removing hover pointer

- src/views/account/Account.tsx
- src/views/bundle/Bundle.tsx
- src/views/bundler/Bundler.tsx
- src/views/factory/Factory.tsx
- src/views/recentBlockActivity/recentBlockActivity.tsx
- src/views/recentBundles/Bundles.tsx
- src/views/recentPaymentMaster/recentPaymentMaster.tsx
- src/views/recentUserOps/UserOperations.tsx
- src/views/topBundlers/TopBundlers.tsx
- src/views/topFactories/TopFactories.tsx
- src/views/topPaymasters/TopPaymasters.tsx
- src/views/userOp/UserOperation.tsx
I fixed the issue where the font of the Breadcrumbs were incorrect, now its displayed with Roboto font.  Fixes #91
> FIXED Breadcrumbs font is incorrect

- src/views/userOp/UserOperation.tsx
> tabbed section query param

- src/views/userOp/DeveloperDetails.tsx
> decodedCallData 2 new sigs

- src/components/common/apiCalls/jiffyApis.tsx
- src/views/userOp/TransactionDetails.tsx
This PR adds status to the Transaction details
> added status

- src/components/common/chip/ChipDropdown.tsx
Fixed #164 
After update ;-
https://github.com/user-attachments/assets/b30a7ac6-0dbd-49de-8ada-c2e81659fe42
> Fixed Overlapping Dropdown Menus

- src/components/common/constants.ts
This PR fixes the More dropdown bug of the base chain
> fixed-base-ui-bug

- src/components/common/chip/ChipDropdown.tsx
- src/components/global/searchblock/Options.tsx
The dropdown shifted bug fixed
> fixed the chains dropdown shifting issue

- public/images/EduchainLogo.svg
- src/components/common/constants.ts
Adding EDU chain config to explorer (constants.ts)
> Adding educhain to networks

- src/components/global/footer/pages.json
Added Feedback card and Updated Links in the Footer
> Updated link in the footer

- src/views/userOp/Tracer.tsx
- src/views/userOp/UserOperation.tsx
-> Added a view for smaller screen
-> Added input function label
> added input function + mobile view

- src/views/userOp/Tracer.tsx
- src/views/userOp/UserOperation.tsx
> minor fixes and checks

- src/views/userOp/Tracer.tsx
Made the Validdation Payment and Execution accordians to open multiple at once
> made accordians to open multiple at once

- src/views/home/Home.tsx
Temporarily Hiding top paymasters and bundlers for cyber-mainnet
> temporary hide tables for cyber-m

- src/components/common/apiCalls/jiffyApis.tsx
- src/views/bundle/Bundle.tsx
- src/views/bundle/Tracer.tsx
Normal Transaction traces added
> transaction traces added

- src/views/bundle/Bundle.tsx
> mobile view fix

- src/views/bundle/Bundle.tsx
bundle/trx traces added for odyssey
> Tracer section

- src/components/common/chip/Modal.tsx
- src/components/common/table/Table.tsx
- src/views/bundle/BundleNew.tsx
- src/views/factory/Factory.tsx
- src/views/userOp/UserOperation.tsx
> skeleton updated for dark theme

- src/components/common/chip/ChipDropdown.tsx
- src/components/common/chip/Modal.tsx
> added dark theme for networks card

- src/components/common/NetworkSelector.tsx
- src/components/common/chip/Chip.tsx
- src/components/common/chip/ChipDropdown.tsx
- src/components/common/table/Table.tsx
- src/views/bundle/BundleNew.tsx
- src/views/recentBundles/Bundles.tsx
- src/views/recentPaymentMaster/TransactionDetails.tsx
- src/views/recentPaymentMaster/recentPaymentMaster.tsx
- src/views/recentUserOps/UserOperations.tsx
- src/views/topBundlers/TopBundlers.tsx
- src/views/topPaymasters/TopPaymasters.tsx
- src/views/userOp/UserOpLogs.tsx
- src/views/userOp/UserOperation.tsx
Some Changes in Network Selector chips +
All four Tables
> minor changes in chip + tables

- src/views/topFactories/TopFactories.tsx
> top factories page update

- src/components/common/Logo.tsx
- src/components/common/chip/Chip.tsx
- src/components/global/navbar/Navbar.tsx
- src/views/home/Home.tsx
- src/views/tx/BundleNew.tsx
- src/views/tx/Tracer.tsx
- src/views/userOp/Tracer.tsx
Improving v2 Performance, Page load and reducing Api Calls
> improving LCP + large layout shifts (Performance Optimization)

- src/components/common/copy_button/CopyButton.tsx
- src/components/global/navbar/Navbar.tsx
- src/views/tx/BundleNew.tsx
- src/views/tx/Tracer.tsx
- src/views/userOp/Tracer.tsx
- src/views/userOp/UserOperation.tsx
Preloading Tracers to optimize page load 
Reducing LCPs
> preloading tracers + lcps

- src/views/tx/BundleNew.tsx
- src/views/userOp/UserOperation.tsx
Appending Section Tabs in the userop and tx url
> appending sections in url

- src/views/tx/BundleNew.tsx
- src/views/userOp/UserOperation.tsx
> dev_details fix

- src/components/common/apiCalls/jiffyApis.tsx
- Refactored API call functions (`getLatestUserOps`, `getTopBundlers`, `getTopPaymasters`, `getTopFactories`, and `getLatestBundles`) for improved readability and robustness.
- Implemented `URLSearchParams` for cleaner and error-free query string construction.
- Added detailed error handling using `try-catch` to gracefully manage network or parsing issues.
- Enhanced response validation to ensure API responses are properly structured before processing.
- Improved toast notifications for better user feedback, distinguishing between warnings and errors.
- Consolidated logic to minimize repetition and ensure maintainability.
> improve API call functions with better error handling(sentry)
